### ISSUE TITLE
trying to edit code

### ISSUE THREAD

**Issue by pac18010** [Roundaround/mc-fabric-sprint-indicator#3]
My wife would like a mod that does the same thing but for crouching, so I'm trying to figure out how to modify the code, and honestly I'm lost. Could you help out, maybe help me learn a bit?

You can reach me on instagram or discord

https://www.instagram.com/sir_crazynut/

Sir_Crazynut

**Comment by Roundaround** [comment]
I'm sorry, but I don't have the time to teach anything. I released the source code here primarily in case anyone wants to contribute (i.e. fix bugs). If you want to use it as a reference for your own mod you're of course welcome to do so but I'm going to be unable to help you in any active way.
